- README.md
-README.md 파일 멤버에 이름을 추가
closes #1
> ReadMe Member추가

- package-lock.json
- package.json
- tailwind.config.js
🏋🏻 Changes
---
🎒 Background
---
closes #7
> Chore: [chore/#7/add_Tailwind_setting] Add Tailwind settings

- src/components/Image/Image.stories.tsx
- src/components/Image/Image.tsx
- src/components/Image/index.ts
🏋🏻 Changes
---
🎒 Background
---
closes #12
> Feat: [feat/#12/image_component] Implement Image component

- src/components/Link/Link.stories.tsx
- src/components/Link/Link.tsx
- src/components/Link/index.ts
🏋🏻 Changes
---
🎒 Background
---
closes #14
> Feat: [feat/#14/link_component] Implement Link component

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- src/components/Input/index.ts
🏋🏻 Changes
---
🎒 Background
---
closes #16
> Feat: [feat/#16/input_component] Implement Input components

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Button/index.ts
🏋🏻 Changes
---
🎒 Background
---
closes #9
> Feat: [feat/#9/Button_component] Implement Button Component

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/DropdownItem.tsx
- src/components/Dropdown/DropdownMenu.tsx
- src/components/Dropdown/index.ts
Dropdown component를 구현하였습니다.
https://user-images.githubusercontent.com/99635366/231032758-09d211d5-edd0-4704-ab22-1e650fce7677.mov
<br>
https://user-images.githubusercontent.com/99635366/231032871-63d02cb0-7421-435a-8c00-0192fa64f26a.mov
<br>
✅ closes #20
> Feat: [Feat/#20/dropdown component] Implement Dropdown component

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/index.ts
Modal Component를 구현합니다. 
https://user-images.githubusercontent.com/111405347/231329367-f44c5142-4ef5-4004-8c9a-27b32442df67.mov
<br>
✅ closes #30
> Feat: [feat/#30/Modal Component] Implement Modal Component

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Image/Image.stories.tsx
- src/components/Image/Image.tsx
- src/components/ImageButton/ImageButton.tsx
- className은 필수로 사용되지 않기에 옵셔널로 변경하였습니다.
- type 이름을 ‘abled’ 에서 ‘active’로 변경하였습니다.
- size에서 basic 크기는 사용하지 않기에 제거하였습니다.
- className으로 바로 활용할 수 있는 color는 type에서 제거하였습니다.
- 버튼 종류별로 button story들을 추가하였습니다.
- 사용되지 않는 imageState 삭제하였습니다.
- 사용되지 않는 User 이미지 파일 삭제하였습니다.
- Figma 시안과 사이즈가 달라서 사이즈 변경하였습니다.
- 이미지 가운데 정렬을 위해 부모 태그에 flex 사용하였습니다.
- 이미지 파일 경로를 바로 삽입하기 위해 기존 logo 이미지 파일을 제거하였습니다.
- src, alt 속성을 사용자가 custom할 수 있도록 변경하였습니다.
- 변경된 사항을 storybook에 반영하였습니다.
<br>
✅ closes #33
> Fix: [Fix/#33/fix components] Fix components

- src/components/Modal/Modal.tsx
- Button component 수정하며 변경 된 'color' 타입을 제거하였습니다. 
<br>
✅ closes #35
> Fix: [Fix/#35/fix components] Fix Modal Components

- src/components/Product/Product.stories.tsx
- src/components/Product/Product.tsx
- src/components/Product/index.ts
메인페이지에서 사용할 Product Component를 구현합니다. 
카테고리/ 시작가/ 현재가는 동적으로 구현하였습니다. 
https://user-images.githubusercontent.com/111405347/231396563-b252e29b-96a9-4384-ae3c-f6b248d528f6.mov
<br>
✅ closes #38
> Feat: [Feat/#38/Main Product] Implement Main Product

- src/pages/Login/Login.stories.tsx
- src/pages/Login/Login.tsx
- src/pages/Login/index.ts
이미지 첨부하겠습니다!
<br>
✅ closes #37
> Feat: Implement Login page

- src/components/Dropdown/Dropdown.tsx
- src/components/Header/Header.tsx
- src/components/Link/Link.tsx
- className은 필수로 사용되지 않기에 옵셔널로 변경하였습니다.
- className을 커스텀하게 변경될 수 있도록 props를 추가하였습니다. 
<br>
✅ closes #41
> Fix: [Fix/#41/fix components] Fix components

- src/components/ProductDetail/ProductDetail.stories.tsx
- src/components/ProductDetail/ProductDetail.tsx
- src/components/ProductDetail/index.ts
상품 상세 페이지에서 사용할 Product Detail Component를 구현합니다.
입력받을 값들은 동적으로 구현하였습니다. 
https://user-images.githubusercontent.com/111405347/231631350-f8118658-ced8-4689-bd99-220438f1e686.mov
<br>
✅ closes #40
> Feat: [Feat/#40/ProductDetail] Implement Product Detail

- src/components/Profile/Profile.stories.tsx
- src/components/Profile/Profile.tsx
- src/components/Profile/index.ts
마이페이지에서 사용할 Profile Component를 구현합니다. 
입력받을 값들은 동적으로 구현하였습니다. 
https://user-images.githubusercontent.com/111405347/231694986-ac7e3a16-ce4a-4a9d-b411-1d8a14b6ecbb.mov
<br>
✅ closes #45
> Feat: [Feat/#45/Profile] Implement Profile Component

- src/components/RadioButton/RadioButton.stories.tsx
- src/components/RadioButton/RadioButton.tsx
페이지에서 사용할 RadioButton Component를 구현합니다.
<br>
✅ closes #48
> Feat: [Feat/#48/RadioButton] Implement Radio Button

- src/components/RadioButton/RadioButton.stories.tsx
- src/components/RadioButton/RadioButton.tsx
페이지에서 사용할 Radio Button을 그룹화하고, Button Style을 변경하였습니다.
https://user-images.githubusercontent.com/111405347/231935408-2576c737-bbd5-4171-94f8-7be57e44ac70.mov
<br>
✅ closes #51
> Fix: [Fix/#51/Radio Button] Fix components

- src/components/Product/Product.tsx
추후 상품 클릭을 위해 cursor-pointer 추가 합니다. 
<br>
✅ closes #56
> Fix: [Fix/#56/Product] Fix Product Component

- src/components/Input/Input.tsx
> Fix: [fix/#62/Image_in_Input] Modify Image position in Input component

- src/components/Header/HeaderTop.tsx
> Fix: [Fix/#65/HeaderTop] Add 'imageType'properties

- src/pages/ProductRegist/ProductRegist.stories.tsx
- src/pages/ProductRegist/ProductRegist.tsx
- src/pages/ProductRegist/index.ts
> Feat: [Feat/#47/ProductRegist] Implement Product Regist Page

- src/pages/ProductDetailPage/ProductDetailPage.stories.tsx
- src/pages/ProductDetailPage/ProductDetailPage.tsx
- src/pages/ProductDetailPage/index.ts
등록된 상품의 상세페이지 구현
<br>
✅ closes #64
> Feat: [Feat/#64/ProductDetailPage] Implement Product Detail Page

- src/pages/DepositPage/DepositPage.stories.tsx
- src/pages/DepositPage/DepositPage.tsx
- src/pages/DepositPage/index.ts
예치금 관리하는 페이지를 구현합니다.
<br>
✅ closes #73
> Feat: [Feat/#73/DepositPage] Implement Deposit Page

- src/pages/PaymentDone/PaymentDone.stories.tsx
- src/pages/PaymentDone/PaymentDone.tsx
> Feat: [Feat/#77/PaymentDone] Implement PaymentDone

- src/pages/SearchPage/SearchPage.stories.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/SearchPage/index.ts
> Feat: [Feat/#75/SearchPage] Implement Search Page

- src/pages/MyBidding/MyBidding.stories.tsx
- src/pages/MyBidding/MyBidding.tsx
- src/pages/MyBidding/index.ts
https://user-images.githubusercontent.com/99635366/232232578-5f1d524f-fb0c-4c33-8321-3f8e4b8059fe.mov
<br>
✅ closes #70
> Feat: [feat/#70/bidding_page] Implement MyBidding page

- src/components/Modal/Modal.tsx
- src/components/ProductDetail/ProductDetail.tsx
- 추가된 태그에 들어가는 type과 id props를 추가하였습니다.
- 불필요한 css 속성을 제거하였습니다.
- 모달 버튼이 배경과 분리되어 있어서, 수정하였습니다.
<br>
✅ closes #
> Fix: [Fix/#80/fix component] Fix Modal, Product Detail component

- src/pages/ProductDetailPage/ProductDetailPage.tsx
> Fix: [fix/#82/fix_productDetail] Fix css in ProductDetail page

- src/pages/PaymentPage/PaymentPage.stories.tsx
- src/pages/PaymentPage/PaymentPage.tsx
https://user-images.githubusercontent.com/111405347/232235576-90c3f86c-9482-477d-9419-c2b6cd29b1e6.mov
<br>
✅ closes #84
> Feat: [Feat/#84/PaymentPage] Implement PaymentPage

- index.html
- package-lock.json
- package.json
- src/components/Header/HeaderNav.tsx
- src/components/Header/HeaderTop.tsx
- src/components/Link/index.ts
- src/components/RadioButton/index.ts
- src/components/TextLink/TextLink.stories.tsx
- src/components/TextLink/TextLink.tsx
- src/components/TextLink/index.ts
- src/main.tsx
- src/pages/DepositPage/DepositPage.tsx
- src/pages/Login/Login.tsx
- src/pages/MyPage/index.ts
- src/pages/PaymentDone/index.ts
- src/pages/ProductDetailPage/index.ts
- src/pages/SearchPage/SearchPage.tsx
- src/pages/SignUp/SignUp.tsx
- export 코드가 빠져 있어서 추가하였습니다.
- react-router-dom의 Link를 사용하기 위해서 이름을 TextLink로 변경하였습니다.
- 페이지간 라우터 연결하였습니다.
- index.html 파일에 사이트 이름 변경하였습니다.
- index.html 파일에 로고 이미지 변경하였습니다.
<br>
✅ closes #86
> Feat: [Feat/#86/router] Implement router between pages

- index.html
- package-lock.json
- package.json
- src/components/Header/HeaderNav.tsx
- src/components/Header/HeaderTop.tsx
- src/components/Link/index.ts
- src/components/RadioButton/index.ts
- src/components/TextLink/TextLink.stories.tsx
- src/components/TextLink/TextLink.tsx
- src/components/TextLink/index.ts
- src/main.tsx
- src/pages/DepositPage/DepositPage.tsx
- src/pages/Login/Login.tsx
- src/pages/MyPage/index.ts
- src/pages/PaymentDone/index.ts
- src/pages/Preparing/Preparing.stories.tsx
- src/pages/Preparing/Preparing.tsx
- src/pages/Preparing/index.ts
- src/pages/ProductDetailPage/index.ts
- src/pages/SearchPage/SearchPage.tsx
- src/pages/SignUp/SignUp.tsx
준비 중인 페이지가 필요해서, Preparing page를 추가 구현하였습니다.
<br>
✅ closes #87
> Feat: [Feat/#87/preparing] Implement Preparing page

- src/components/Product/Product.tsx
연결이 빠졌습니다! 😂
<br>
✅ closes #90
> Feat: [feat/#90/productDetail] Connect product to Product detail page

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- src/pages/PaymentPage/index.ts
- src/pages/ProductRegist/ProductRegist.tsx
Input component와 Product Regist Page 코드 일부 수정합니다.
<br>
✅ closes #92
> Fix: [fix/#92/FixComponent] Fix the Input and Product Regist Page

- src/components/CategoryDetail/CategoryDetail.stories.tsx
- src/components/CategoryDetail/CategoryDetail.tsx
- src/components/CategoryDetail/index.ts
- src/components/ProductDetail/ProductDetail.stories.tsx
- src/components/ProductDetail/ProductDetail.tsx
- src/components/ProductPrice/ProductPrice.stories.tsx
- src/components/ProductPrice/ProductPrice.tsx
- src/components/ProductPrice/index.ts
- src/components/ProductTime/ProductTime.stories.tsx
- src/components/ProductTime/ProductTime.tsx
- src/components/ProductTime/index.ts
- src/components/Title/Title.stories.tsx
- src/components/Title/Title.tsx
- src/components/Title/index.ts
- src/pages/PaymentPage/PaymentPage.tsx
- src/pages/ProductDetailPage/ProductDetailPage.tsx
- Product Detail Component를 분리합니다. 
- Title, ProductTime, ProductPrice Component 각각 생성
- Product Detail이 사용되는 페이지도 추가로 수정합니다. 
<br>
✅ closes #96
> Feat: [feat/#96/Separate_component] Separate and Implement Component

- src/components/ImageRegist/ImageRegist.stories.tsx
- src/components/ImageRegist/ImageRegist.tsx
- src/components/ImageRegist/index.ts
- src/components/MinBeedingPrice/MinBeedingPrice.stories.tsx
- src/components/MinBeedingPrice/MinBeedingPrice.tsx
- src/components/MinBeedingPrice/index.ts
- src/components/ProductCategory/ProductCategory.stories.tsx
- src/components/ProductCategory/ProductCategory.tsx
- src/components/ProductCategory/index.ts
- src/components/ProductInfo/ProductInfo.stories.tsx
- src/components/ProductInfo/ProductInfo.tsx
- src/components/ProductInfo/index.ts
- src/components/ProductName/ProductName.stories.tsx
- src/components/ProductName/ProductName.tsx
- src/components/ProductName/index.ts
- src/components/ProductStartPrice/ProductStartPrice.stories.tsx
- src/components/ProductStartPrice/ProductStartPrice.tsx
- src/components/ProductStartPrice/index.ts
- src/components/ProductStatus/ProductStatus.stories.tsx
- src/components/ProductStatus/ProductStatus.tsx
- src/components/ProductStatus/index.ts
- src/pages/ProductRegist/ProductRegist.stories.tsx
- src/pages/ProductRegist/ProductRegist.tsx
- ImageRegist 구현
- MinBeedingPrice 구현
- ProductInfo 구현
- ProductName 구현
- ProductStartPrice 구현
- ProductStatus 구현
<br>
✅ closes #100
> Feat: [Feat/#100/FeatComponent] Separate Product Detail Component and Implement component

- src/pages/Login/Login.tsx
- src/pages/Login/components/KakaoLogin/KakaoLogin.stories.tsx
- src/pages/Login/components/KakaoLogin/KakaoLogin.tsx
- src/pages/Login/components/KakaoLogin/index.ts
- src/pages/Login/components/LoginForm/LoginForm.stories.tsx
- src/pages/Login/components/LoginForm/LoginForm.tsx
- src/pages/Login/components/LoginForm/index.ts
- src/pages/Login/components/LoginTitle/LoginTitle.stories.tsx
- src/pages/Login/components/LoginTitle/LoginTitle.tsx
- src/pages/Login/components/LoginTitle/index.ts
- src/pages/SignUp/SignUp.tsx
- src/pages/SignUp/components/SignUpForm/SignUpForm.stories.tsx
- src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
- src/pages/SignUp/components/SignUpForm/index.ts
- src/pages/SignUp/components/SignUpTitle/SignUpTitle.stories.tsx
- src/pages/SignUp/components/SignUpTitle/SignUpTitle.tsx
- src/pages/SignUp/components/SignUpTitle/index.ts
컴포넌트 분리 작업을 하였습니다!
<br>
✅ closes #102
> Refactor: [Refactor/#102/separate component] Refactor components in pages

- src/components/ProductCategory/ProductCategory.stories.tsx
추가적으로 필요한 설명을 작성합니다.
<br>
✅ closes #105
> Style: [style/#105/fix_name] Change Title name in storybook file

- src/api/ProductInfo/getProductInfo.ts
- src/queries/useProductInfoQuery.tsx
> Config: [config/#112] Add API & Query folder

- src/components/MinBeedingPrice/MinBeedingPrice.tsx
- src/components/ProductName/ProductName.tsx
- src/components/ProductStartPrice/ProductStartPrice.tsx
- 경매 상품 등록 상태값을 받아오기 위해 기능을 추가합니다.
- Enhancement MinBiddingPrice
- Enhancement ProductName
- Enhancement ProductStartPrice
<br>
✅ closes #110
> Enhancement: [Enhancement/#110] Enhancement component for product regist

- src/pages/Login/components/LoginForm/LoginForm.tsx
- src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
영상 첨부하겠습니다.
<br>
✅ closes #103
> Feat: [Feat/#103/validation] Implement Login, SignUp validation

- src/components/EndDateTime/EndDateTime.stories.tsx
- src/components/EndDateTime/EndDateTime.tsx
- src/components/EndDateTime/index.ts
- src/components/StartDateTime/StartDateTime.stories.tsx
- src/components/StartDateTime/StartDateTime.tsx
- src/components/StartDateTime/index.ts
- Implement Start Date Time Component
- Implement End Date Time Component
<br>
✅ closes #118
> Feat: [feat/#118/DateTimeComponent] Implement Start/End DateTime component

- src/components/DateTimePicker/DateTimePicker.tsx
> Feat: [feat/#116/DateTimePicker] Add DateTimePicker Library

- src/components/Input/Input.tsx
- src/pages/Login/components/LoginForm/LoginForm.tsx
- src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
> Fix: [fix/#114/add_type] Add password type in Input component

- src/components/ProductStatus/ProductStatus.tsx
- src/components/RadioButton/RadioButton.tsx
- Enhancement Radio Button Component
- Fix the Product Status Component
<br>
✅ closes #128
> Enhancement: [#128/RadioButton] Enhancement Radio Button

- src/main.tsx
> Docs: [Docs/#126] Add Token value

- src/api/ProductInfo/getProductInfo.ts
- src/components/ProductInfo/ProductInfo.tsx
> Enhancement: [Enhancement/#124] Add description API & Enhancement product info component

- src/components/Dropdown/DropdownMenu.tsx
- src/components/ProductCategory/ProductCategory.tsx
- Dropdown 변경값을 받아오는 추가 기능 구현
- 상위 컴포넌트인 Product Category 도 함께 수정
<br>
✅ closes #122
> Enhancement: [Enhancement/#122/Dropdown] Enhancement Dropdown/ Product Category component

- src/components/DateTimePicker/DateTimePicker.tsx
- src/components/EndDateTime/EndDateTime.tsx
- src/components/StartDateTime/StartDateTime.tsx
- Date Time Picker 변경된 값을 가져오도록 기능을 추가 구현 합니다.
<br>
✅ closes #130
> Enhancement: [Enhancement/#130/DateTimePicker] Enhance Date Time Picker

- src/main.tsx
BrowserRouter를 사용하여 라우터 구조를 수정합니다.
<br>
✅ closes #132
> Fix: [Fix/#132/Router] Fix the Router structure

- src/pages/ProductRegist/ProductRegist.tsx
- 상품 등록시 필요한 정보를 서버로 전송
- 모든 정보가 전송되면, /mypage로 이동
- 이미지 등록은 제외하고 우선 필드 값만 받아서 전송합니다.
<br>
✅ closes #134
> Feat: [feat/#134/ProductRegist] Implement Product Regist

- package-lock.json
- package.json
- src/api/ProductInfo/getProductInfo.ts
> Config :[Config/#136] Config and Add Library

- src/pages/MyPage/MyPage.tsx
> Fix: [Fix/#142] Fix the Tab List

- src/api/ProductInfo/getProductInfo.ts
- src/components/ImageRegist/ImageRegist.tsx
- src/pages/ProductRegist/ProductRegist.tsx
- src/queries/useProductInfoQuery.tsx
- Multi Part File 로 이미지 업로드 구현
- 그에 따른 API / Query 코드 수정
<br>
✅ closes #144
> Enhancement: [Enhancement/#144] Implement image upload with multi-part-file

- src/pages/MyBidding/MyBidding.tsx
> Fix: [fix/#147/type_error] Fix type error

- src/queries/useProductInfoQuery.tsx
추가적으로 필요한 설명을 작성합니다.
<br>
✅ closes #149
> Fix: [fix/#149/import_code] Fix import code

- src/api/ProductInfo/getProductInfo.ts
- src/queries/useProductInfoQuery.tsx
> Fix: [Fix/#151] Fix API from files to imageSrc

- src/components/MinBeedingPrice/MinBeedingPrice.tsx
- src/components/ProductStartPrice/ProductStartPrice.tsx
- src/pages/ProductRegist/ProductRegist.tsx
- 숫자로만 입력 받을 수 있도록 유효성 검사 기능을 추가 합니다. 
<br>
✅ closes #
> Enhancement: [Enhancement/#153] MinBiddingPrice & StartPrice validation

- src/types/images.d.ts
- tsconfig.json
> Fix: [fix/#161/type_error] Fix errors when adding images in tsx file

- src/pages/SignUp/components/SignUpTitle/SignUpTitle.tsx
> Fix: [fix/#165/image] Modify image path to absolute path

- src/pages/Login/components/LoginForm/LoginForm.tsx
추가했던 Link 태그를 삭제하였습니다.
<br>
✅ closes #167
> Fix: [fix/#167/login_page] Delete Link tag in LoginForm component

- src/setProxy.js
- vite.config.ts
드디어 CORS 해결 완료하였습니다!!! 🎉🎉🎉
<br>
✅ closes #169
> Fix: [Fix/#169/cors error] Add proxy code to vite config file

- src/api/SignUpInfo/user.ts
- src/hook/useSignUp.ts
- src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
CORS에러와 씨름 후, 자체 회원가입 기능 구현 완료 하였습니다.
로그인 기능 구현 후, 추가 기능 구현하겠습니다.
- 이메일 중복 체크
- 전화번호 인증
<br>
✅ closes #121
> Feat: [feat/#121/signup] Implement member signup

- src/components/EndDateTime/EndDateTime.tsx
- src/components/StartDateTime/StartDateTime.tsx
- src/pages/ProductRegist/ProductRegist.tsx
- 경매시작시간 : 현재보다 이전 시간 선택시 에러메시지 띄움
- 경매종료시간 : 시작시간보다 이전 시간 선택시 에러메시지 띄움
<br>
✅ closes #173
> Enhancemet: [Enhancement/#173] StartDateTime & EndDateTime validation

- src/api/ProductInfo/getProductInfo.ts
- src/pages/ProductRegist/ProductRegist.tsx
- src/queries/useProductInfoQuery.tsx
- 'imagesSrc' -> 'files'로 수정
<br>
✅ closes #175
> Fix: [Fix/#175] Fix the API name from 'imagesSrc' to 'files'

- src/components/ProductDetail/ProductDetail.tsx
간격 조절 안된 부분 스타일 수정합니다.
<br>
✅ closes #177
> Fix: [Fix/#177] Fix page style

- package-lock.json
- package.json
- src/api/LoginInfo/user.ts
- src/components/Header/Header.tsx
- src/hook/useLogin.ts
- src/main.tsx
- src/pages/Login/components/LoginForm/LoginForm.tsx
- src/pages/ProductDetailPage/ProductDetailPage.tsx
- src/recoil/atom.ts
- 로그인 기능 구현 완료하였습니다. (추가 기능 구현하겠습니다)
- 헤더 레이아웃이 로그인 유무에 따라 변경되지 않아, 조건에 따른 헤더 레이아웃이 변경되도록 전역상태 관리를 통해 구현하였습니다.
- 전역상태 관리를 위해 Recoil을 설치하였습니다.
<br>
✅ closes #172
> Feat: [Feat/#172/login] Implement Login

- index.html
https://wellsw.tistory.com/34
<br>
✅ closes #180
> Bug: [bug/#180/mixed_content_error] Add code to resolve mixed content error

- src/components/Product/Product.tsx
- src/main.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/MyPage/MyPage.tsx
- src/pages/SearchPage/SearchPage.stories.tsx
- src/pages/SearchPage/SearchPage.tsx
- 더미데이터 추가 후 상품 불러오는 코드 추가 
- 드롭다운 z-index 추가
- 상품 추가, 제거 됨에 따라 노출되는 count 수 변경 
<br>
✅ closes #
> Enhancement: [Enhancement/#182] Enhancement Product / Search Page

- src/components/ProductStatus/ProductStatus.tsx
- src/components/RadioButton/RadioButton.tsx
- 지정된 enum값으로 Radio Button Status 수정 
<br>
✅ closes #184
> Fix: [Fix/#184] Fix the Radio Button status

- src/pages/MainPage/MainPage.tsx
배너 높이가 너비에 따라 유동적으로 변하게 되어서 해당 이미지 높이를 고정으로 두고, 변동이 없을 수 있게끔 조절하였습니다.
<br>
✅ closes #186
> Fix: [fix/#186/banner] Fix banner size

- src/hook/useLogin.ts
- src/hook/useSignUp.ts
- src/setProxy.js
- vite.config.ts
> Fix: [fix/#188/server] Change Server address

- src/components/Dropdown/DropdownMenu.tsx
- 지정된 enum값으로 Dropdown category menu 수정
<br>
✅ closes #
> Fix: [Fix/#192] Fix the dropdown category menu

- src/components/Header/HeaderNav.tsx
경매 결과 -> 지난 경매로 Header title 변경
<br>
✅ closes #190
> Fix: [Fix/#190] Fix the Header title

- src/api/ProductInfo/getProductInfo.ts
- src/pages/ProductRegist/ProductRegist.tsx
- src/queries/useProductInfoQuery.tsx
- 서버 주소 변경에 따른 백엔드 서버 주소를 변경합니다. 
<br>
✅ closes #196
> Fix: [Fix/#196] Fix the BE server address

- src/pages/MainPage/MainPage.tsx
- Dummy data 를 추가하고 상품을 화면에 렌더링하도록 수정합니다
<br>
✅ closes #194
> Enhancement: [Enhancement/#194] Add dummydata on Main Page

- src/components/Button/Button.stories.tsx
- src/pages/ProductDetailPage/ProductDetailPage.tsx
- 추가로 필요한 price button을 생성합니다
- 상품 디테일 페이지에서 button 상태관리 기능을 추가 합니다 (이 기능 따로 pr 올리려고 했는데 한 번에 올려버리는 실수를..😂)
<br>
✅ closes #198
> Enhancement:[Enhancement/#198] Add price button component / Implement button status

- package-lock.json
- package.json
- src/api/ProductInfo/getFixInfo.ts
- src/pages/ProductFix/ProductFix.stories.tsx
- src/pages/ProductFix/ProductFix.tsx
- src/pages/ProductFix/index.ts
- src/queries/useFixInfoQuery.tsx
- tsconfig.json
- 상품 수정 페이지를 추가하고 그에 따른 기능을 구현합니다
<br>
✅ closes #200
> Feat: [Feat/#200] Implement product modify page

- src/main.tsx
상품 수정 페이지 라우터를 추가 합니다.
<br>
✅ closes #201
> Fix: [fix/#201] Add productfix router

- src/components/Dropdown/DropdownMenu.tsx
- 카테고리로 상품 검색시 상품 정렬 되는 속성을 수정합니다.
<br>
✅ closes #205
> Fix: [Fix/#205] Fix the category properties

- src/pages/MyPage/MyPage.tsx
- src/pages/Participated/Participated.stories.tsx
- src/pages/Participated/Participated.tsx
- src/pages/Participated/index.ts
- src/pages/Purchased/Purchased.stories.tsx
- src/pages/Purchased/Purchased.tsx
- src/pages/Purchased/index.ts
- src/pages/Registered/Registered.stories.tsx
- src/pages/Registered/Registered.tsx
- src/pages/Registered/index.ts
- 각각의 탭에 맞는 화면을 렌더링 하도록 코드를 수정합니다
<br>
✅ closes #207
> Enhancement: [Enhancement/#207] Enhancement rendering of product list

- src/api/ProductInfo/getProductInfo.ts
- src/components/ImageRegist/ImageRegist.tsx
- src/pages/ProductRegist/ProductRegist.tsx
- 이미지 파일을 객체형태로 넘겨주도록 코드 수정
<br>
✅ closes #209
> Fix: [Fix/#209] Fix the code of product regist

- src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
상태값을 변경하고, 잘못 commit 된 번호 인증 코드를 삭제하였습니다..😅
<br>
✅ closes #213
> Fix: [ Fix/#213/button ] Change Duplication button state

- src/components/Image/Image.tsx
- src/components/Product/Product.stories.tsx
- src/components/Product/Product.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/Participated/Participated.tsx
- src/pages/Preparing/Preparing.tsx
- src/pages/Purchased/Purchased.tsx
- src/pages/Registered/Registered.tsx
- src/pages/SearchPage/SearchPage.tsx
- Product 컴포넌트 내부에 imagesSrc API 추가
- 받아온 데이터 화면에 렌더링 하도록 코드 수정
<br>
✅ closes #215
> Enhancement: [Enhancement/#215] Fix product component for image rendering

- src/components/Input/Input.tsx
- src/pages/SignUp/components/SignUpForm/SignUpForm.tsx
전화번호 및 인증번호로 인증하기 구현 완료하였습니다. 
그에 따른 인증번호 input 추가로, placeholder 및 해당 타입 추가하였습니다!!
<br>
✅ closes #217
> Feat: [ Feat/#217/validate number ] Implement Validate number

- src/pages/SearchPage/SearchPage.tsx
- AuctionStatus에 따라 데이터 받아오도록 코드 수정
- 데이터가 없을때 에러 처리하고 그에 맞는 화면 렌더링
<br>
✅ closes #219
> Enhancement: [enhancement/#219] Fix page  and add error code status

- src/pages/Registered/Registered.tsx
- 내가 등록한 경매 데이터를 받아서 화면에 렌더링 되도록 코드 수정
<br>
✅ closes #221
> Enhancement: [Enhancement/#221] Enhancement register page for data rendering

- src/pages/Upcoming/Upcoming.stories.tsx
- src/pages/Upcoming/Upcoming.tsx
- src/pages/Upcoming/index.ts
- AuctionStatus에 따라 데이터 받아오도록 코드 수정
- 화면 렌더링 구현
<br>
✅ closes #223
> Enhancement: [Enhancement/#223] Fix upcoming page

- src/pages/Result/Result.stories.tsx
- src/pages/Result/Result.tsx
- src/pages/Result/index.ts
- AuctionStatus로 데이터 불러오기
- 화면에 렌더링 해줍니당
<br>
✅ closes #225
> Enhancement: [enhancement/#225] Fix the result bidding page

- src/main.tsx
- 예정경매, 지난경매 라우터를 수정하고 추가합니다. 
<br>
✅ closes #227
> Fix: [Fix/#227] Fix the router

- src/components/Profile/Profile.tsx
- 마이페이지 '내역보기' 클릭시 예치금 관리 페이지로 연결
<br>
✅ closes #229
> Enhancement: [Enhancement/#229] Link to deposit page

- src/pages/MainPage/MainPage.tsx
> Fix: [fix/#231/main_layout] Adjust the main page product layout

- src/pages/Participated/Participated.tsx
- src/pages/ParticipatedBidding/ParticipatedBidding.stories.tsx
- src/pages/ParticipatedBidding/ParticipatedBidding.tsx
- src/pages/ParticipatedBidding/index.ts
- 내가 참여한 경매 페이지 데이터 불러오기
- 화면 렌더링
<br>
✅ closes #233
> Enhancement: [enhancement/#233] Enhancement the page

- src/pages/Preparing/Preparing.tsx
> Fix: [fix/#235/preparing] Modify components to make them reusable

- src/pages/Result/Result.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/Upcoming/Upcoming.tsx
> Fix: [fix/#237/error_page] Add error page

- src/components/Header/HeaderNav.tsx
- src/main.tsx
- src/pages/Information/Information.stories.tsx
- src/pages/Information/Information.tsx
- src/pages/Information/index.ts
> Feat: [Feat/#241/info page] Implement Information page

- src/components/Header/HeaderNav.tsx
Header navigation이 active 된 것과 되지 않은 것이 구분되지 않아, 아래와 같이 스타일 변경하였습니다. <br>
<br>
✅ closes #245
> Feat: [feat/#245/header_nav] Change header navigation style

- src/main.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/Result/Result.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/Upcoming/Upcoming.tsx
> Fix: [Fix/#249/change list] Change render auction list

- src/main.tsx
- src/pages/ProductDetailModify/ProductDetailModify.stories.tsx
- src/pages/ProductDetailModify/ProductDetailModify.tsx
- src/pages/ProductDetailModify/index.ts
- src/pages/ProductFix/ProductFix.tsx
- 상품 수정 기능 추가 구현
- 라우더 추가
<br>
✅ closes #251
> Feat: [feat/#251] Implement product modify

- src/pages/Login/components/KakaoLogin/KakaoLogin.tsx
카카오 로그인 URL 연결하였습니다.
<br>
✅ closes #253
> Feat: [feat/#253/kakao_login] Connect Kakao login URL

- src/components/RegisteredProduct/RegisteredProduct.tsx
- src/components/RegisteredProduct/RegisteredProdut.stories.tsx
- src/components/RegisteredProduct/index.ts
- src/pages/Registered/Registered.tsx
- 마이 페이지 '내가 등록한' 상품을 수정할 수 있습니다
<br>
✅ closes #255
> Enhancement: [enhancement/#255] Enhancement product modify page

- src/pages/MainPage/MainPage.tsx
- 메인 페이지에서 불러오는 데이터를 수정합니다
<br>
✅ closes #257
> Fix: [Fix/#257] Fix the main page

- src/components/Product/Product.tsx
- src/components/ProductDetail/ProductDetail.tsx
- src/components/Title/Title.tsx
- src/main.tsx
- src/pages/MainPage/MainPage.tsx
- src/pages/Participated/Participated.tsx
- src/pages/ProductDetailPage/ProductDetailPage.tsx
- src/pages/Purchased/Purchased.tsx
- src/pages/Result/Result.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/Upcoming/Upcoming.tsx
- tsconfig.json
Detail 페이지 연결 완료!!!!
<br>
✅ closes #259
> Feat: [Feat/#259/detail page] Connect Detail page
